worker_processes auto;
events {
    worker_connections 2048;
}

stream {
    # Paramètres de stabilité globale et de fluidité
    proxy_timeout 3600s;
    proxy_connect_timeout 10s;
    tcp_nodelay on;

    # Premier VPS d'origine
    upstream backend_443 {
        server 191.96.235.32:443;
    }
    
    # Second VPS (gestion du panel et des protocoles sécurisés en TLS sur le port 443)
    upstream vless_backend {
        server 79.133.42.185:443;
    }
    
    upstream trojan_backend {
        server 79.133.42.185:443;
    }
    
    upstream vmess_backend {
        server 79.133.42.185:443;
    }

    upstream socks_backend {
        server 79.133.42.185:443;
    }

    # Redirection générale vers le premier VPS
    server {
        listen 8080;
        proxy_pass backend_443;
    }

    # Redirection des protocoles vers le port 443 du second VPS
    server {
        listen 10001;
        proxy_pass vless_backend;
    }

    server {
        listen 10002;
        proxy_pass trojan_backend;
    }

    server {
        listen 10003;
        proxy_pass vmess_backend;
    }

    server {
        listen 2004;
        proxy_pass socks_backend;
    }
}
