worker_processes auto;
events {
    worker_connections 2048;
}

stream {
    # Paramètres de stabilité globale et de fluidité
    proxy_timeout 3600s;
    proxy_connect_timeout 10s;
    tcp_nodelay on;

    upstream backend {
        server 191.96.235.32:443;
    }
    
    upstream vless_backend {
        server 79.133.42.185:10001;
    }
    
    upstream trojan_backend {
        server 79.133.42.185:10002;
    }
    
    upstream vmess_backend {
        server 79.133.42.185:10003;
    }

    upstream socks_backend {
        server 79.133.42.185:2004;
    }

    server {
        listen 8080;
        proxy_pass backend;
    }

    server {
        listen 10001;
        proxy_pass vless_backend;
    }

    server {
        listen 10002;
        proxy_pass trojan_backend;
    }

    server {
        listen 10003;
        proxy_pass vmess_backend;
    }

    server {
        listen 2004;
        proxy_pass socks_backend;
    }
}
