worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    upstream backend {
        server 217.217.225.14:443;
    }
    
    server {
        listen 8080;
        proxy_pass backend;
    }
}
